spring:
  application:
    name: taskapp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '123456'
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.taskapp.model
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.example.taskapp: DEBUG
