import { Injectable, signal, computed, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export type Language = 'en' | 'km';

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private readonly platformId = inject(PLATFORM_ID);
  private readonly isBrowser = isPlatformBrowser(this.platformId);

  readonly currentLang = signal<Language>(this.getInitialLang());

  private readonly translations: Record<Language, Record<string, string>> = {
    en: {
      'app.title': 'TaskFlow Pro',
      'nav.main': 'Main',
      'nav.security': 'Security',
      'nav.tasks': 'Tasks',
      'nav.users': 'Users',
      'nav.permissions': 'Permissions',
      'nav.change-password': 'Change Password',
      'auth.logout': 'Logout',
      'auth.signin': 'Sign in',
      'auth.signup': 'Sign up',
      'common.search': 'Search',
      'common.status': 'Status',
      'common.role': 'Role',
      'common.actions': 'Actions',
      'common.reset': 'Reset',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.add': 'Add',
      'common.close': 'Close',
      'common.close_others': 'Close Others',
      'common.close_right': 'Close Tabs to Right',
      'common.close_all': 'Close All Tabs',
      'common.by': 'By',
      'common.description': 'Description',
      'common.created_by': 'Created By',
      'common.created_date': 'Created Date',
      'common.updated_by': 'Updated By',
      'common.updated_date': 'Updated Date',
      'user.list.title': 'User Management',
      'user.list.subtitle': 'Manage your team and their access levels.',
      'user.add': 'Add User',
      'user.edit': 'Edit User',
      'user.username': 'Username',
      'user.email': 'Email',
      'user.password': 'Password',
      'auth.invalid_token': 'Invalid or expired reset token.',
      'user.confirm_password': 'Confirm Password',
      'auth.change_password_title': 'Change Password',
      'auth.update_password': 'Update Password',
      'user.new_password': 'New Password',
      'user.force_reset': 'Force Password Change on Login',
      'user.enabled': 'Enabled',
      'user.active': 'Active',
      'user.inactive': 'Inactive',
      'user.roles': 'Roles',
      'task.create': 'Create Task',
      'task.title': 'Task Title',
      'task.description': 'Description',
      'task.submit': 'Submit Form',
      'dashboard.welcome': 'Welcome back',
      'dashboard.total_users': 'Total Users',
      'dashboard.active_users': 'Active Users',
      'dashboard.pending_users': 'Pending Users',
      'dashboard.open_tasks': 'Open Tasks',
      'dashboard.recent_users': 'Recent Users',
      'dashboard.view_all': 'View all',
      'common.showing': 'Showing',
      'common.of': 'of',
      'common.users': 'users',
      'common.rows_per_page': 'Rows per page:',
      'task.new': 'Create New Task',
      'common.no_tasks': 'No tasks found. Create one to get started.',
      'common.completed': 'Completed',
      'common.pending': 'Pending',
      'role.subtitle': 'Manage access levels and capabilities for each system role.',
      'role.add': 'Add Role',
      'role.save_permissions': 'Save Permissions',
      'role.feature': 'Feature',
      'role.view': 'View',
      'role.create': 'Create',
      'role.update': 'Update',
      'role.delete': 'Delete',
      'role.edit': 'Edit Role',
      'role.edit_subtitle': 'Manage system roles and their descriptive metadata.',
      'role.add_subtitle': 'Create a new security role to define system access levels.',
      'role.name': 'Role Name',
      'role.name_placeholder': 'e.g. MANAGER',
      'role.description': 'Description',
      'role.description_placeholder': 'Enter a clear description of what this role can do...',
      'confirm.user.delete.title': 'Delete User',
      'confirm.user.delete.message': 'Are you sure you want to delete this user? This action cannot be undone.',
      'confirm.user.update.title': 'Update User',
      'confirm.user.update.message': 'Are you sure you want to save these changes?',
      'confirm.user.status.title': 'Update User Status',
      'confirm.user.status.message': 'Are you sure you want to update this user\'s status?',
      'confirm.task.delete.title': 'Delete Task',
      'confirm.task.delete.message': 'Are you sure you want to delete this task? This action cannot be undone.',
      'confirm.task.update.title': 'Update Task',
      'confirm.task.update.message': 'Are you sure you want to update this task\'s status?',
      'confirm.role.delete.title': 'Delete Role',
      'confirm.role.delete.message': 'Are you sure you want to delete this role? All associated permissions will be removed.',
      'confirm.role.update.title': 'Update Role',
      'confirm.role.update.message': 'Are you sure you want to save these changes to the role?',
      'confirm.permission.save.title': 'Save Permissions',
      'confirm.permission.save.message': 'Are you sure you want to save all permission changes?',
    },
    km: {
      'app.title': 'ប្រព័ន្ធគ្រប់គ្រងការងារ',
      'nav.main': 'ទំព័រដើម',
      'nav.security': 'សុវត្ថិភាព',
      'nav.tasks': 'ការងារ',
      'nav.users': 'អ្នកប្រើប្រាស់',
      'nav.permissions': 'សិទ្ធិ',
      'nav.change-password': 'ប្តូរលេខសម្ងាត់',
      'auth.logout': 'ចាកចេញ',
      'auth.signin': 'ចូលប្រើ',
      'auth.signup': 'ចុះឈ្មោះ',
      'common.search': 'ស្វែងរក',
      'common.status': 'ស្ថានភាព',
      'common.role': 'តួនាទី',
      'common.actions': 'សកម្មភាព',
      'common.reset': 'កំណត់ឡើងវិញ',
      'common.cancel': 'បោះបង់',
      'common.save': 'រក្សាទុក',
      'common.edit': 'កែសម្រួល',
      'common.delete': 'លុប',
      'common.add': 'បន្ថែម',
      'common.close': 'បិទ',
      'common.close_others': 'បិទផ្ទាំងផ្សេងទៀត',
      'common.close_right': 'បិទផ្ទាំងទៅខាងស្តាំ',
      'common.close_all': 'បិទផ្ទាំងទាំងអស់',
      'common.by': 'ដោយ',
      'common.description': 'ការពិពណ៌នា',
      'common.created_by': 'បង្កើតដោយ',
      'common.created_date': 'កាលបរិច្ឆេទបង្កើត',
      'common.updated_by': 'កែប្រែដោយ',
      'common.updated_date': 'កាលបរិច្ឆេទកែប្រែ',
      'user.list.title': 'ការគ្រប់គ្រងអ្នកប្រើប្រាស់',
      'user.list.subtitle': 'គ្រប់គ្រងក្រុមការងារ និងកម្រិតសិទ្ធិចូលប្រើប្រាស់របស់អ្នក។',
      'user.add': 'បន្ថែមអ្នកប្រើប្រាស់',
      'user.edit': 'កែសម្រួលអ្នកប្រើប្រាស់',
      'user.username': 'ឈ្មោះអ្នកប្រើ',
      'user.email': 'អ៊ីមែល',
      'user.password': 'លេខសម្ងាត់',
      'auth.invalid_token': 'តំណភ្ជាប់មិនត្រឹមត្រូវ ឬហួសសុពលភាព។',
      'user.confirm_password': 'បញ្ជាក់លេខសម្ងាត់',
      'auth.change_password_title': 'ប្តូរលេខសម្ងាត់',
      'auth.update_password': 'ធ្វើបច្ចុប្បន្នភាពលេខសម្ងាត់',
      'user.new_password': 'លេខសម្ងាត់ថ្មី',
      'user.force_reset': 'តម្រូវឱ្យប្តូរលេខសម្ងាត់ពេលចូលប្រើលើកដំបូង',
      'user.enabled': 'បើកដំណើរការ',
      'user.active': 'កំពុងដំណើរការ',
      'user.inactive': 'ផ្អាកដំណើរការ',
      'user.roles': 'តួនាទី',
      'task.create': 'បង្កើតកិច្ចការ',
      'task.title': 'ចំណងជើងកិច្ចការ',
      'task.description': 'ការពិពណ៌នា',
      'task.submit': 'បញ្ជូនទិន្នន័យ',
      'dashboard.welcome': 'សូមស្វាគមន៍មកវិញ',
      'dashboard.total_users': 'អ្នកប្រើប្រាស់សរុប',
      'dashboard.active_users': 'អ្នកប្រើប្រាស់សកម្ម',
      'dashboard.pending_users': 'អ្នកប្រើប្រាស់រង់ចាំ',
      'dashboard.open_tasks': 'កិច្ចការបើកចំហ',
      'dashboard.recent_users': 'អ្នកប្រើប្រាស់ថ្មីៗ',
      'dashboard.view_all': 'មើលទាំងអស់',
      'common.showing': 'បង្ហាញ',
      'common.of': 'នៃ',
      'common.users': 'អ្នកប្រើប្រាស់',
      'common.rows_per_page': 'ចំនួនជួរដេកក្នុងមួយទំព័រ:',
      'task.new': 'បង្កើតកិច្ចការថ្មី',
      'common.no_tasks': 'រកមិនឃើញកិច្ចការទេ។ បង្កើតមួយដើម្បីចាប់ផ្តើម។',
      'common.completed': 'បានបញ្ចប់',
      'common.pending': 'កំពុងរង់ចាំ',
      'role.subtitle': 'គ្រប់គ្រងកម្រិតចូលប្រើប្រាស់ និងសិទ្ធិសម្រាប់តួនាទីប្រព័ន្ធនីមួយៗ។',
      'role.add': 'បន្ថែមតួនាទី',
      'role.save_permissions': 'រក្សាទុកសិទ្ធិ',
      'role.feature': 'លក្ខណៈពិសេស',
      'role.view': 'មើល',
      'role.create': 'បង្កើត',
      'role.update': 'កែប្រែ',
      'role.delete': 'លុប',
      'role.edit': 'កែសម្រួលតួនាទី',
      'role.edit_subtitle': 'គ្រប់គ្រងតួនាទីប្រព័ន្ធ និងព័ត៌មានលម្អិតរបស់ពួកគេ។',
      'role.add_subtitle': 'បង្កើតតួនាទីសុវត្ថិភាពថ្មីដើម្បីកំណត់កម្រិតចូលប្រើប្រាស់ប្រព័ន្ធ។',
      'role.name': 'ឈ្មោះតួនាទី',
      'role.name_placeholder': 'ឧ. អ្នកគ្រប់គ្រង',
      'role.description': 'ការពិពណ៌នា',
      'role.description_placeholder': 'បញ្ចូលការពិពណ៌នាច្បាស់លាស់អំពីអ្វីដែលតួនាទីនេះអាចធ្វើបាន...',
      'confirm.user.delete.title': 'លុបអ្នកប្រើប្រាស់',
      'confirm.user.delete.message': 'តើអ្នកពិតជាចង់លុបអ្នកប្រើប្រាស់នេះមែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
      'confirm.user.update.title': 'កែប្រែអ្នកប្រើប្រាស់',
      'confirm.user.update.message': 'តើអ្នកពិតជាចង់រក្សាទុកការផ្លាស់ប្តូរទាំងនេះមែនទេ?',
      'confirm.user.status.title': 'កែប្រែស្ថានភាពអ្នកប្រើប្រាស់',
      'confirm.user.status.message': 'តើអ្នកពិតជាចង់កែប្រែស្ថានភាពអ្នកប្រើប្រាស់នេះមែនទេ?',
      'confirm.task.delete.title': 'លុបកិច្ចការ',
      'confirm.task.delete.message': 'តើអ្នកពិតជាចង់លុបកិច្ចការនេះមែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
      'confirm.task.update.title': 'កែប្រែកិច្ចការ',
      'confirm.task.update.message': 'តើអ្នកពិតជាចង់កែប្រែស្ថានភាពកិច្ចការនេះមែនទេ?',
      'confirm.role.delete.title': 'លុបតួនាទី',
      'confirm.role.delete.message': 'តើអ្នកពិតជាចង់លុបតួនាទីនេះមែនទេ? សិទ្ធិពាក់ព័ន្ធទាំងអស់នឹងត្រូវលុបចេញ។',
      'confirm.role.update.title': 'កែប្រែតួនាទី',
      'confirm.role.update.message': 'តើអ្នកពិតជាចង់រក្សាទុកការផ្លាស់ប្តូរទាំងនេះទៅក្នុងតួនាទីមែនទេ?',
      'confirm.permission.save.title': 'រក្សាទុកសិទ្ធិ',
      'confirm.permission.save.message': 'តើអ្នកពិតជាចង់រក្សាទុកការផ្លាស់ប្តូរសិទ្ធិទាំងអស់មែនទេ?',
    },
  };

  translate(key: string): string {
    return this.translations[this.currentLang()][key] || key;
  }

  setLanguage(lang: Language): void {
    this.currentLang.set(lang);
    if (this.isBrowser) {
      localStorage.setItem('lang', lang);
      document.documentElement.lang = lang;
    }
  }

  private getInitialLang(): Language {
    if (this.isBrowser) {
      const saved = localStorage.getItem('lang') as Language;
      if (saved === 'en' || saved === 'km') return saved;
    }
    return 'en';
  }
}
